name: CI
on: [push, pull_request]

jobs:
  fmt:
    name: fmt ${{ github.sha }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  ci:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        task: [['check', ''], ['test', ''], ['clippy', '-- --deny warnings'], ['build', '--release']]

    name: ${{ matrix.task[0] }} ${{ github.sha }} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.0.0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.task[0] }}
          args: ${{ matrix.task[1] }}

      - uses: actions/upload-artifact@v1.0.0
        # This action doesn’t work on Windows due to something weird with paths.
        if: matrix.task[0] == 'build' && matrix.os != 'windows-latest'
        with:
          name: ${{ matrix.os }}-${{ github.sha }}
          path: target/release/strand

